### ISSUE TITLE
Collaborations with others

### ISSUE THREAD

**Issue by DonaldTsang** [ThePlasmaRailgun/TXQR-Android#1]
It would be good to add a ReadMe detailing the relationship between this repo and https://github.com/divan/txqr and how it works under the hood.

**Comment by NovaLogicDev** [comment]
Good suggestion, the thing primarily to know is that due to technical limitations of integrating GO into android the actual project doesn't integrate the code from txqr at all, rather it has a custom implementation inspired by txqr. Depending on my scheduling I'll put together a readme sometime around the same time we finish integrating QrStreamer, which creates the code gifs.

**Comment by DonaldTsang** [comment]
- Terminal based https://github.com/leonjza/qrxfer/issues/2
- Animated QR art https://github.com/EFPrefix/EFQRCode/issues/56
- Static QR https://github.com/JamesCullum/file2qr/issues/1
- https://github.com/keith-turner/qrcv/issues/1
- https://github.com/cedricmartel/QrCodeTransfer/issues/1
- https://github.com/xloem/qrstream/issues/33
- https://github.com/mihaigiurgeanu/cold-widow/issues/2
- https://github.com/Neohapsis/QRCode-Video-Data-Exfiltration/issues/5
- https://github.com/anderson-/Eye-Fi/issues/2
- https://github.com/huanghq/flipqr/issues/1
